services:
  app:
    container_name: app
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: