services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "9090:8080"
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  host_network:
    external: true
    name: host